spring.application.name=mobile_Application
spring.datasource.url= jdbc:postgresql://localhost:5432/sms
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

#Enable simple cache
#spring.cache.type=simple

spring.cache.type=redis
spring.cache.host=localhost
spring.cache.port=6379


management.endpoints.web.exposure.include=*

springdoc.swagger-ui.path=/poori